apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "store-ui.fullname" . }}-test-connection"
  labels:
    {{- include "store-ui.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['{{ include "store-ui.fullname" . }}:{{ .Values.service.port }}/actuator/health/liveness']
  restartPolicy: Never

