apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-orders
  namespace: argocd
spec:
  project: shmueli-retail-store
  source:
    repoURL: 'https://github.com/shmueliitay/shmueli-retail-store-INT.git'
    targetRevision: main
    path: src/orders/chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
