apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-checkout
  namespace: argocd
spec:
  project: shmueli-retail-store
  source:
    repoURL: 'https://github.com/shmueliitay/shmueli-retail-store-INT.git'
    targetRevision: main
    path: src/checkout/chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
      - /metadata/labels/app.kubernetes.io/version
